LambdaAddHotel:
  handler: functions.addHotel.handler.handler
  role: LambdaRole
  events:
    - http:
        path: addHotel
        method: POST
        cors:
          origin: '*' # Replace '*' with specific origin if needed
          allowHeaders:
            - Authorization
            - Content-Type
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
  environment:
    bucketName: !Ref HotelBookingBucket
    dynamodb: !Ref DynamoDBTable
    REGION: ${self:provider.region}
  layers:
    - { Ref: PythonRequirementsLambdaLayer }
